version: "3.5"
services:
  frontend:
    build:
      context: .
    working_dir: /var/www/html/app/
    entrypoint: npm run dev -- -o --host
    ports:
      - 3001:3000
    volumes:
      - .:/var/www/html/app
    tty: true
networks:
  dove:

